---

- name: Create a new file
  hosts: nodes
  tasks:

    - name: Change file ownership, group, and permissions
      ansible.builtin.file:
        path: /tmp/example2
        owner: root
        group: root
        mode: '0644'
        state: touch

    - name: Remove previous file
      ansible.builtin.file:
        path: /tmp/example1
        state: absent